DirectoryPath: "doc/build/site"
IgnoreDirs:
  - "0.5.4"
  - "0.6.0"
  - "0.6.1"
  - "0.6.2"
  - "0.6.3"
IgnoreURLs:
  - "//www.allen-heath.com/"
  - "//github.com/Deep-Symmetry/beat-link-trigger/edit/"
  - "//liberapay.com/"
  - "//linktr.ee/"
  - "//opensource.org/licenses/"
  - "//packetsender.com"
  - "//unix.stackexchange.com/questions/405229/"
  - "//www.miglayout.com"
  - "//www.wireshark.org"
