DirectoryPath: "doc/build/site"
IgnoreDirs:
  - "0.5.4"
  - "0.6.0"
  - "0.6.1"
  - "0.6.2"
  - "0.6.3"
IgnoreURLs:
  - "//opensource.org/licenses/"
  - "//liberapay.com/"
  - "//github.com/Deep-Symmetry/beat-link-trigger/edit/main/doc/modules/ROOT/"
