name: Create 端berjar and Windows MSI

on: [push]

jobs:
  build_uberjar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Determine release tag
      run: echo "::set-env name=release_tag::`git describe --abbrev=0`"
    - name: Install dependencies
      run: lein deps
    - name: Install antora
      run: sudo npm i -g @antora/cli @antora/site-generator-default
    - name: Build 端berjar
      run: lein uberjar
    - name: Upload 端berjar
      uses: Xotl/cool-github-releases@v1
      if: success()
      with:
        mode: update
        tag_name: ${{ env.release_tag }}
        assets: target/beat-link-trigger.jar
        github_token: ${{ github.token }}

  build_msi:
    runs-on: windows-latest

#    needs:
#      build_uberjar
    steps:
    - uses: actions/checkout@v1
    - name: Determine release tag and MSI name
      run: |
        $releaseTag = $( git describe --abbrev=0 )
        echo "::set-env name=release_tag::$releaseTag"
        $versionTag = ($releaseTag).replace("-SNAPSHOT","")
        echo "::set-env name=version_tag::$versionTag"
        $msiName = "Beat Link Trigger-$versionTag.msi"
        echo "::set-env name=msi_name::msiName"
    - uses: actions/setup-java@v1
      with:
        java-version: '14-ea'
    - name: Download 端berjar
      uses: Xotl/cool-github-releases@v1
      with:
        mode: download
        tag_name: ${{ env.release_tag }}
        assets: beat-link-trigger.jar
        github_token: ${{ github.token }}
    - name: Build Windows Installer
      run: .\.github\scripts\build_msi.ps1
    - name: Upload Windows MSI
      uses: Xotl/cool-github-releases@v1
      if: success()
      with:
        mode: update
        tag_name: ${{ env.release_tag }}
        assets: ${{ env.msi_name }}
        github_token: ${{ github.token }}
