name: Create überjar

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Install antora
      run: npm i -g @antora/cli @antora/site-generator-default
    - name: Build überjar
      run: lein uberjar
