name: Create überjar and Windows MSI

on: [push]

jobs:
  build_uberjar:
    name: Build cross-platform überjar
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Determine release tag and snapshot status
      run: |
        RELEASE_TAG=$(git describe --abbrev=0)
        echo "::set-env name=release_tag::$RELEASE_TAG"
        if [[ $RELEASE_TAG =~ .*-SNAPSHOT ]]
        then
          echo "::set-env name=release_snapshot::true"
        else
          echo "::set-env name=release_snapshot::false"
        fi

    - name: Cache Leiningen dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-lein-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-lein-

    - name: Install dependencies
      run: lein deps

    - name: Install antora
      run: sudo npm i -g @antora/cli @antora/site-generator-default

    - name: Build überjar
      run: lein uberjar

    - name: Delete pre-existing preview release
      if: success() && env.release_snapshot
      continue-on-error: true
      uses: Xotl/cool-github-releases@v1
      with:
        mode: delete
        tag_name: ${{ env.release_tag }}
        github_token: ${{ github.token }}

    - name: Upload überjar
      if: success()
      uses: Xotl/cool-github-releases@v1
      with:
        mode: update
        tag_name: ${{ env.release_tag }}
        isPrerelease: true
        assets: target/beat-link-trigger.jar
        github_token: ${{ github.token }}
        body_mrkdwn: |
          :construction: This is pre-release code for people who want to help test [what is going into the next release](https://github.com/Deep-Symmetry/beat-link-trigger/blob/master/CHANGELOG.md).

          > Don’t download this if you aren’t comfortable testing code while it is under active development! Instead, look at the [latest release](https:///github.com/Deep-Symmetry/beat-link-trigger/releases/latest).

          You will need your own Java runtime in order to run the executable `beat-link-trigger.jar` below (you will need to click expand the **Assets** section if you don’t see it).

          Also, please note that since it’s a snapshot release, the content of this release will change frequently—whenever new code is pushed to the project—so you will want to _download the latest version of the jar every time you work with it_.

  build_msi:
    runs-on: windows-latest

    needs:
      build_uberjar

    steps:
    - uses: actions/checkout@v1

    - name: Determine release tag and MSI name
      run: |
        $releaseTag = $( git describe --abbrev=0 )
        echo "::set-env name=release_tag::$releaseTag"
        $versionTag = ($releaseTag).replace("-SNAPSHOT","").replace("v","")
        echo "::set-env name=version_tag::$versionTag"
        $msiName = "Beat Link Trigger-$versionTag.msi"
        echo "::set-env name=msi_name::$msiName"
        $artifactName = "Beat-Link-Trigger-$versionTag-Win64.msi"
        echo "::set-env name=artifact_name::$artifactName"

    - uses: actions/setup-java@v1
      with:
        java-version: '14-ea'

    - name: Download überjar
      uses: Xotl/cool-github-releases@v1
      with:
        mode: download
        tag_name: ${{ env.release_tag }}
        assets: beat-link-trigger.jar
        github_token: ${{ github.token }}

    - name: Cache bundled OpenJDK runtime
      uses: actions/cache@v1
      with:
        path: Runtime
        key: ${{ runner.os }}-bundled-jdk

    - name: Build Windows Installer
      run: .\.github\scripts\build_msi.ps1

    - name: Upload Windows MSI
      if: success()
      uses: Xotl/cool-github-releases@v1
      with:
        mode: update
        tag_name: ${{ env.release_tag }}
        assets: ${{ env.artifact_name }}
        github_token: ${{ github.token }}
