name: Create überjar and Windows MSI

on: [push]

jobs:
  build_uberjar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Determine release tag
      run: echo "::set-env name=release_tag::`git describe --abbrev=0`"
    - name: Install dependencies
      run: lein deps
    - name: Install antora
      run: sudo npm i -g @antora/cli @antora/site-generator-default
    - name: Build überjar
      run: lein uberjar
    - name: Delete pre-existing preview release
      if: success()
      continue-on-error: true
      uses: Xotl/cool-github-releases@v1
      with:
        mode: delete
        tag_name: ${{ env.release_tag }}
        github_token: ${{ github.token }}
    - name: Upload überjar
      if: success()
      uses: Xotl/cool-github-releases@v1
      with:
        mode: update
        tag_name: ${{ env.release_tag }}
        assets: target/beat-link-trigger.jar
        github_token: ${{ github.token }}
        body_mrkdwn: |
          :construction: This is pre-release code for people who want
          to help test [what is going into the next
          release](https://github.com/Deep-Symmetry/beat-link-trigger/blob/master/CHANGELOG.md).

          > Don’t download this if you aren’t comfortable testing code
          > while it is under active development! Instead, look at the
          > [latest
          > release](https:///github.com/Deep-Symmetry/beat-link-trigger/releases/latest).

          You will need your own Java runtime in order to run the
          executable `beat-link-trigger.jar` below (you will need to
          click expand the **Assets** section if you don’t see it).

          Also, please note that since it’s a snapshot release, the
          content of this release will change frequently—whenever new
          code is pushed to the project—so you will want to _download
          the latest version of the jar every time you work with it_.

  build_msi:
    runs-on: windows-latest

    needs:
      build_uberjar
    steps:
    - uses: actions/checkout@v1
    - name: Determine release tag and MSI name
      run: |
        $releaseTag = $( git describe --abbrev=0 )
        echo "::set-env name=release_tag::$releaseTag"
        $versionTag = ($releaseTag).replace("-SNAPSHOT","").replace("v","")
        echo "::set-env name=version_tag::$versionTag"
        $msiName = "Beat Link Trigger-$versionTag.msi"
        echo "::set-env name=msi_name::$msiName"
    - uses: actions/setup-java@v1
      with:
        java-version: '14-ea'
    - name: Download überjar
      uses: Xotl/cool-github-releases@v1
      with:
        mode: download
        tag_name: ${{ env.release_tag }}
        assets: beat-link-trigger.jar
        github_token: ${{ github.token }}
    - name: Build Windows Installer
      run: .\.github\scripts\build_msi.ps1
    - name: Upload Windows MSI
      if: success()
      uses: Xotl/cool-github-releases@v1
      with:
        mode: update
        tag_name: ${{ env.release_tag }}
        assets: ${{ env.msi_name }}
        github_token: ${{ github.token }}
