name: Create überjar

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Check target version
      run: lein v
    - name: Build überjar
      run: lein uberjar
