name: Create überjar

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Determine release tag
      run: echo "::set-env name=release_tag::`git describe --abbrev=0`"
    - name: Install dependencies
      run: lein deps
    - name: Install antora
      run: sudo npm i -g @antora/cli @antora/site-generator-default
    - name: Build überjar
      run: lein uberjar
    - name: Upload überjar
      uses: Xotl/cool-github-releases@v1
      if: success()
      with:
        mode: update
        tag_name: ${{ env.release_tag }}
        assets: target/beat-link-trigger.jar
        github_token: ${{ github.token }}
