name: Create überjar

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Install antora
      run: sudo npm i -g @antora/cli @antora/site-generator-default
    - name: Build überjar
      run: lein uberjar
    - name: Archive überjar
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: blt-jar
        path: target/beat-link-trigger.jar
